repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: check-added-large-files
        args:
        - --maxkb=128
    -   id: check-ast
    -   id: check-case-conflict
    -   id: check-docstring-first
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-xml
    -   id: check-yaml
    -   id: detect-private-key
    -   id: end-of-file-fixer
    -   id: mixed-line-ending
        args: [ '--fix=lf' ]
        description: Forces to replace line ending by the UNIX 'lf' character.
    -   id: fix-encoding-pragma
    -   id: name-tests-test
        args:
        - --django
        exclude: ^tests/testapp|^tests/management/|^tests/collisions/|^tests/pythonrc.py|^tests/runner.py
-   repo: https://github.com/pycqa/flake8
    rev: '7.1.1'
    hooks:
    -   id: flake8
-   repo: https://github.com/tox-dev/pyproject-fmt
    rev: v2.5.0
    hooks:
    -   id: pyproject-fmt
-   repo: https://github.com/trbs/pre-commit-hooks-trbs.git
    rev: 1.2.4
    hooks:
    -   id: forbid-executables
        exclude: manage.py|setup.py
