language: python

python:
  - 2.6
  - 2.7

env:
  - DJANGO_VERSION=1.4
  - DJANGO_VERSION=1.3

install:
  - pip install -q Django==$DJANGO_VERSION --use-mirrors
  - pip install PyYAML unittest2 flake8 --use-mirrors
  - pip install -q -e . --use-mirrors

script:
  - flake8 --ignore=E501,W391 .
  - python setup.py test
